'use client';
import { useState } from 'react';
import { CheckCheck, Users, FileClock } from 'lucide-react';
import { useBoard } from '../lib/store';
import { departments } from '../data/departments';
import { assignAdvisor, recordStage, remaining, reviewConfirmation, unconfirmedReason } from '../lib/rules';
import type { Department, Roadmap, Student } from '../lib/types';
import { Badge, DepartmentGuide, ErrorMessage, HistoryList, StatusMessage } from './shared';
export function AdminBoard() {
  const { data } = useBoard(); const [filter, setFilter] = useState('all'); const [reason, setReason] = useState('all');
  const rows = data.students.flatMap(s => s.roadmaps.map(r => ({ student: s, roadmap: r, department: departments.find(d => d.id === r.departmentId)! }))).filter(row => filter === 'all' || row.department.id === filter);
  const unconfirmed = rows.filter(row => unconfirmedReason(row.roadmap, row.department) !== '확정 완료'); const pending = rows.filter(row => row.roadmap.application?.status === '승인' && row.roadmap.application.review !== '검토 완료'); const reasons = [...new Set(unconfirmed.map(row => unconfirmedReason(row.roadmap, row.department)))];
  return <><div className="page-heading"><div><div className="eyebrow">행정실 워크스페이스</div><h1>함께 보는 졸업 준비<span className="heading-dot">.</span></h1><p>학과별 진행 상태를 확인하고, 필요한 학생에게 다음 길을 열어 주세요.</p></div><label className="user-picker">학과별 필터<select aria-label="학과별 필터" value={filter} onChange={e => { setFilter(e.target.value); setReason('all'); }}><option value="all">전체 학과</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>
    <div className="summary-strip"><div><Users size={21}/><span>관리 대상 전공</span><strong>{rows.length}<small>건</small></strong></div><div><FileClock size={21}/><span>미확정 전공</span><strong>{unconfirmed.length}<small>건</small></strong></div><div><CheckCheck size={21}/><span>확정 검토 필요</span><strong>{pending.length}<small>건</small></strong></div></div>
    <section className="panel"><div className="section-heading"><h2>사유별 미확정 학생</h2><Badge tone="amber">예시 데이터</Badge></div><div className="filter-chips"><button className={reason === 'all' ? 'selected' : ''} onClick={() => setReason('all')}>전체 {unconfirmed.length}</button>{reasons.map(r => <button className={reason === r ? 'selected' : ''} key={r} onClick={() => setReason(r)}>{r} {unconfirmed.filter(row => unconfirmedReason(row.roadmap, row.department) === r).length}</button>)}</div><div className="unconfirmed-list">{unconfirmed.filter(row => reason === 'all' || unconfirmedReason(row.roadmap, row.department) === reason).map(({ student: s, roadmap: r, department: d }) => <a key={s.id + d.id} href={`#record-${s.id}-${d.id}`}><span><strong>{s.name}</strong><small>{d.name}</small></span><Badge tone="neutral">{unconfirmedReason(r, d)}</Badge></a>)}</div>{!unconfirmed.length && <p className="empty">모든 대상의 지도교수가 확정되었습니다.</p>}{data.students.some(s => !s.configured) && <p className="muted small">전공 설정 전 학생: {data.students.filter(s => !s.configured).map(s => s.name).join(', ')} · 학생 화면에서 설정 후 관리 대상에 포함됩니다.</p>}</section>
    <section className="panel"><div className="section-heading"><h2>교수별 정원</h2><span className="muted">정원 적용 학과만 집계</span></div><div className="capacity-grid">{data.professors.filter(p => filter === 'all' || p.departmentId === filter).map(p => { const d = departments.find(d => d.id === p.departmentId)!; return <article key={p.id}><div><strong>{p.name}</strong><small>{d.name}</small></div>{d.usesCapacity ? <><Badge tone={remaining(p) ? '' : 'amber'}>{remaining(p) ? `남은 자리 ${remaining(p)}명` : '정원 마감'}</Badge><p>{p.assigned}명 배정 / {p.capacity}명 정원</p><div className="progress-track"><span style={{ width: `${p.capacity ? p.assigned / p.capacity * 100 : 0}%` }}/></div></> : <p className="muted">정원 미적용</p>}</article>; })}</div></section>
    <section className="panel" id="applications"><div className="section-heading"><h2>학생별 · 전공별 진행 현황</h2><span className="muted">신청 현황과 확정 검토</span></div><div className="admin-records">{rows.map(row => <AdminRecord key={row.student.id + row.department.id} {...row}/>)}</div>{data.students.flatMap(s => s.majors.filter(m => departments.find(d => d.id === m.departmentId)?.requirements[m.type] === '면제' && (filter === 'all' || m.departmentId === filter)).map(m => <div className="exempt-row" key={s.id + m.departmentId}><strong>{s.name}</strong><span>{departments.find(d => d.id === m.departmentId)?.name} · 복수전공</span><Badge>논문 면제</Badge></div>))}</section>
    <HistoryList events={data.history.filter(h => filter === 'all' || h.departmentId === filter)} students={data.students}/><section className="panel" id="guide">{departments.filter(d => filter === 'all' || d.id === filter).map(d => <DepartmentGuide key={d.id} department={d}/>)}</section>
  </>;
}
function AdminRecord({ student: s, roadmap: r, department: d }: { student: Student; roadmap: Roadmap; department: Department }) {
  const { data, change } = useBoard(); const [feedback, setFeedback] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [professorId, setProfessorId] = useState(data.professors.find(p => p.departmentId === d.id)?.id ?? '');
  const a = r.application; const current = d.stages[r.currentStage]; const run = (fn: Parameters<typeof change>[0], msg: string) => { try { change(fn); setError(''); setMessage(msg); } catch (e) { setError((e as Error).message); setMessage(''); } }; const ctx = () => ({ actor: '가상 행정실', at: new Date().toISOString() });
  return <article id={`record-${s.id}-${d.id}`} className="admin-record" data-testid={`admin-${s.id}-${d.id}`}><div className="section-heading"><h3>{s.name}<small>{d.name} · {s.majors.find(m => m.departmentId === d.id)?.type === 'primary' ? '주전공' : '복수전공'}</small></h3><Badge tone={a?.review === '검토 완료' ? '' : 'amber'}>{unconfirmedReason(r, d)}</Badge></div><div className="record-overview"><p><span>현재 단계</span><strong>{current?.name ?? '전체 완료'}</strong></p><p><span>지도교수</span><strong>{data.professors.find(p => p.id === a?.professorId)?.name ?? '미배정'}</strong></p><p><span>신청 상태</span><strong>{a?.status ?? '미신청'}</strong></p><p><span>서류 상태</span><strong>{current ? r.submitted.includes(current.id) ? '제출 완료' : current.kind === 'result' || current.kind === 'advisor' ? '확인 대기' : '미제출' : '완료'}</strong></p></div>
    <details><summary>전공 진행 단계와 신청 상세</summary><ol className="compact-stages">{d.stages.map((stage, index) => <li key={stage.id}><span>{stage.name}</span><span>{r.completed.includes(stage.id) ? '완료' : stage.kind === 'advisor' && a?.status === '승인' ? a.review : index === r.currentStage ? '진행 중' : '예정'} · {r.submitted.includes(stage.id) ? '제출 기록 있음' : stage.deadline || '정보 확인 필요'}</span></li>)}</ol>{a && <div className="feedback"><p>연구 주제: {a.topic}</p><p>연구계획: {a.plan}</p><p>신청일: {a.requestedAt.slice(0, 10)}</p>{a.feedback && <p>교수 피드백: {a.feedback}</p>}{a.reviewFeedback && <p>행정실 피드백: {a.reviewFeedback}</p>}</div>}</details>
    {a?.status === '승인' && a.review !== '검토 완료' && <div className="review-form"><label>확정 검토 피드백<textarea aria-label={`${s.name} ${d.name} 확정 검토 피드백`} value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="보완 요청 사유를 입력해 주세요"/></label><div className="action-row"><button className="button primary" onClick={() => run(state => reviewConfirmation(state, departments, s.id, d.id, '검토 완료', feedback, ctx()), '지도교수 확정 검토를 완료했습니다.')}>검토 완료</button><button className="button secondary" onClick={() => run(state => reviewConfirmation(state, departments, s.id, d.id, '보완 요청', feedback, ctx()), '학생에게 보완 요청을 전달했습니다.')}>보완 요청</button></div></div>}
    {d.advisorMethod === 'course_assigned' && !a && <div className="inline-form"><label>배정할 지도교수<select aria-label={`${s.name} 배정할 지도교수`} value={professorId} onChange={e => setProfessorId(e.target.value)}>{data.professors.filter(p => p.departmentId === d.id).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button secondary" onClick={() => run(state => assignAdvisor(state, departments, s.id, d.id, professorId, ctx()), '수업 배정 결과를 등록했습니다.')}>지도교수 배정</button></div>}
    {current?.kind === 'result' && <button className="button secondary" onClick={() => run(state => recordStage(state, departments, s.id, d.id, true, ctx()), '최종 결과를 확인했습니다.')}>결과 확인 완료</button>}
    <ErrorMessage message={error}/><StatusMessage message={message}/>
  </article>;
}
